version: '3.3'
services:
  go:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: stoplight-sample-app
    volumes:
      - '.:/go/src/app'
    ports:
      - '8055:8055'
    tty: true
    stdin_open: true